# Generated by Django 6.0.6 on 2026-06-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва завдання')),
                ('time', models.TimeField(verbose_name='Час виконання')),
                ('completed', models.BooleanField(default=False, verbose_name='Виконано')),
                ('category', models.CharField(choices=[('Робота', 'Робота'), ("Здоров'я", "Здоров'я"), ('Їжа', 'Їжа'), ('Відпочинок', 'Відпочинок'), ('Навчання', 'Навчання'), ('Інше', 'Інше')], max_length=50, verbose_name='Категорія')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Завдання',
                'verbose_name_plural': 'Завдання',
                'ordering': ['time'],
            },
        ),
    ]
