# Generated by Django 6.0.6 on 2026-06-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва задачі')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('completed', models.BooleanField(default=False, verbose_name='Виконано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Дедлайн')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачі',
                'ordering': ['-created_at'],
            },
        ),
    ]
